Replace of seg_ms_lesion_mp2rage by UNIseg model on sct_deepseg
ivadomed/model-seg-ms-mp2rage pull request #82
Opened 2024-05-29 22:03 UTC by Nilser3

# Description 

This PR replace the current `seg_ms_lesion_mp2rage` model by `UNIseg` (single-class 3D nnUnet model discused here #75 ) keeping the same name:  `seg_ms_lesion_mp2rage` (after comparisons these models see #81 )
Updates also the README file, explaining how to use the model, datasets for training and acknowledgments to the collaborators.

2024-06-07 14:18 UTC, jcohenadad commented on README.md
> +Charidimos Tsagkas and Daniel Reich from Translational Neuroradiology Section, National Institutes of Health (NIH), Bethesda, USA, Cristina Granziera from Neurologic Clinic and Policlinic, University
```suggestion
- Charidimos Tsagkas (Translational Neuroradiology Section, National Institutes of Health, Bethesda, USA)
- Daniel Reich (Translational Neuroradiology Section, National Institutes of Health, Bethesda, USA)
- Cristina Granziera (Neurologic Clinic and Policlinic, University Hospital Basel and University of Basel, Basel, Switzerland)
- Virginie Callot (Center for Magnetic Resonance in Biology and Medicine, CRMBM-CEMEREM, UMR 7339, CNRS, Aix-Marseille University, Marseille, France)
```

2024-06-07 14:19 UTC, jcohenadad commented on README.md
> +[SCT 6.3](https://spinalcordtoolbox.com/)
```suggestion
[SCT 6.4](https://spinalcordtoolbox.com/)
```

2024-06-07 14:20 UTC, jcohenadad commented on README.md
> +2. Cropping with dilation (for images with 1mm isotropic resolution)
```suggestion
2. Cropping with dilation (for axial images with 1mm isotropic resolution)
```

2024-06-07 14:22 UTC, jcohenadad requested changes
@Nilser3 indicate where to find model to test

2024-06-10 22:05 UTC, Nilser3 commented
> @Nilser3 indicate where to find model to test

Thanks you @jcohenadad 
The model is here https://github.com/ivadomed/model_seg_ms_mp2rage/releases/tag/r20240610 

I have already replaced the `seg_ms_lesion_mp2rage` model and it is ready to be tested this branch:
SCT log: `86d5f8d5a473e5e034d365726a548d96776da755`
branch: `nlm/update-_seg_ms_lesion_mp2rage-model`

2024-06-11 14:28 UTC, jcohenadad commented
Getting this message during inference:
```console
/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/utilities/plans_handling/plans_handler.py:37: UserWarning: Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.
  warnings.warn("Detected old nnU-Net plans format. Attempting to reconstruct network architecture "
```
any concerns?

2024-06-11 14:28 UTC, jcohenadad commented
Another message, possibly concerning:
```console
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

```

2024-06-11 14:36 UTC, jcohenadad requested changes
The [zipped model](https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20240610/model_ms_lesion_mp2rage-unit1_3d.zip) does not seem to include the list of subjects used for training and the version of the dataset used to train the model. It is required.

2024-06-11 14:42 UTC, jcohenadad commented
Inference time is pretty long... I've tried without cropping on the basel data, inference time was 4min 6s.

With cropping:

2024-06-11 14:43 UTC, jcohenadad commented
Related question: the progress bar shows 100 iterations:
```console
 19%|█████████████████████████████▊                                                                                                                               | 19/100 [00:42<02:52,  2.14s/it]
```
What to these correspond to? And how come the number of iterations is the same across different input volume size?

2024-06-11 15:04 UTC, jcohenadad commented
Comparison with previous model, and current model with various crop sizes:

![ezgif-6-1f1309b0b4](https://github.com/ivadomed/model_seg_ms_mp2rage/assets/2482071/5aa9a9fd-1d8e-458c-ba1a-fabca43cb8ab)

Conclusion: too narrow cropping (5x5x5) leads to bad segmentation. A minimum cropping size is required. What size? @Nilser3 that's a follow-up investigation

2024-06-11 15:09 UTC, jcohenadad commented
> Conclusion: too narrow cropping (5x5x5) leads to bad segmentation. A minimum cropping size is required. What size? @Nilser3 that's a follow-up investigation

follow-up idea: given that the inference is _sliiiiightly_ different across crop sizes, how about computing a soft segmentation based on the inference performed across various crop sizes?

2024-06-17 00:11 UTC, Nilser3 commented
> The [zipped model](https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20240610/model_ms_lesion_mp2rage-unit1_3d.zip) does not seem to include the list of subjects used for training and the version of the dataset used to train the model. It is required.

Thank you @jcohenadad,
Ok, the [release r20240610](https://github.com/ivadomed/model_seg_ms_mp2rage/releases/tag/r20240610) has been updated with the needed information!

2024-09-05 14:43 UTC, jcohenadad commented
@Nilser3 any update?

2024-09-06 10:54 UTC, Nilser3 commented
> @Nilser3 any update? this is becoming urgent: https://forum.spinalcordmri.org/t/segmentation-of-spinal-cord-lesion-on-mp2rage-uni-images-doesnt-work/1302

The model was replaced in the [release 6.4](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/6.4), this branch is ok for PR.

2024-09-06 10:54 UTC, merged